{
 "title": "Humidity Sensor Dashboard",
 "time": { "from": "2026-05-01T03:18:43.934Z", "to": "2026-05-06T11:18:43.934Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latest Temperature Reading",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT temperature FROM sensor_readings ORDER BY TIME DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Latest Humidity Reading",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT humidity FROM sensor_readings ORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Time Since Last Reading (s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT \n  EXTRACT(EPOCH FROM (NOW() - MAX(time))) AS time_since_last_reading\nFROM \n  sensor_readings\nWHERE \n  $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT temperature, \"time\" FROM sensor_readings ORDER BY time DESC LIMIT 1440;"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT humidity, \"time\" FROM sensor_readings ORDER BY time DESC LIMIT 1440;"
    }
   ]
  },
  {
   "title": "Sensor Readings",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "sensors_db",
     "rawSql": "SELECT \"time\", temperature, humidity FROM sensor_readings ORDER BY time DESC LIMIT 50"
    }
   ]
  }
 ]
}